Implement config_entries
Danielhiversen/home_assistant_adax pull request #4
Opened 2020-09-16 19:06 UTC by gjohansson-ST

Hi

I have added the option to use config_entries i.e. configure the integration also using the integration page directly in HA

**NOTE**: I took the liberty of changing the parameter account_id with username instead

I have also changed accordingly in readme + info docs

2020-09-17 09:39 UTC, Danielhiversen requested changes
Thanks. :+1

Why change from account_id to username?

It is called account id in the Adax app, so I think that makes the most sense. Username can also easily be confused by login username for Adax

2020-09-17 09:39 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +"""Adds config flow for Mill integration."""
Mill -> adax
```suggestion
"""Adds config flow for Adax integration."""
```

2020-09-17 09:39 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +    """Handle a config flow for Mill integration."""
Mill -> adax
```suggestion
    """Handle a config flow for Adax integration."""
```

2020-09-17 09:39 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +        """
Remove the string

2020-09-17 09:39 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +            async with session.post(ACCESS_TOKEN_URL, data=data) as response:
```suggestion
            async with session.post(API_URL + '/auth/token', data=data) as response:
```

2020-09-17 09:40 UTC, Danielhiversen requested changes

2020-09-17 09:40 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +        async with aiohttp.ClientSession() as session:
Do not create a new session, but use 
`from homeassistant.helpers.aiohttp_client import async_get_clientsession
`

2020-09-17 12:20 UTC, gjohansson-ST commented
> Thanks. 👍 
> 
> 
> 
> Why change from account_id to username?
> 
> 
> 
> It is called account id in the Adax app, so I think that makes the most sense. Username can also easily be confused by login username for Adax

Ok. Not a big problem so I'll change it back together with the other small things to change from your review.

2020-09-21 05:22 UTC, Danielhiversen requested changes

2020-09-21 05:22 UTC, Danielhiversen commented on README.md
> +    username: "112395"  # replace with your account ID (see Adax WiFi app, Account Section)
```suggestion
    account_id: "112395"  # replace with your account ID (see Adax WiFi app, Account Section)
```

2020-09-21 05:22 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +            raise CannotConnect
```suggestion
        _LOGGER.info("Adax: Failed to login to retrieve token: %d", response.status)
        raise CannotConnect
```

2020-09-21 05:22 UTC, Danielhiversen commented on custom_components/adax/strings.json
> +          "account_id": "[%key:common::config_flow::data::account_id%]",
I do not think this one exists?

2020-09-21 05:22 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +from homeassistant.const import CONF_PASSWORD, CONF_USERNAME
```suggestion
from homeassistant.const import CONF_PASSWORD
```

2020-09-21 05:22 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +                username = user_input["account_id"].replace(" ", "")
```suggestion
                account_id = user_input["account_id"].replace(" ", "")
```

2020-09-21 05:22 UTC, Danielhiversen commented on custom_components/adax/config_flow.py
> +async def validate_input(hass: core.HomeAssistant, username, password):
```suggestion
async def validate_input(hass: core.HomeAssistant, account_id, password):
```

2020-09-21 05:22 UTC, Danielhiversen commented on info.md
> +For versions above 0.2.2 the setting of account_id has been replaced with username.
```suggestion
```

2020-09-21 06:17 UTC, gjohansson-ST commented on custom_components/adax/strings.json
> +          "account_id": "[%key:common::config_flow::data::account_id%]",
Correct

2020-09-21 06:20 UTC, gjohansson-ST commented on README.md
> +    username: "112395"  # replace with your account ID (see Adax WiFi app, Account Section)
Changed back to account_id

2020-09-21 06:25 UTC, gjohansson-ST commented
I think with these last updates it's now accurate. Or at least I hope I didn't forget anything :)

2020-09-21 14:04 UTC, Danielhiversen approved these changes
Thanks

2020-09-21 14:04 UTC, Danielhiversen commented on info.md
> +Enter your account id as username
```suggestion
Enter your account id
```

2020-09-21 14:04 UTC, Danielhiversen commented on info.md
> +    username: "112395"  # replace with your account ID (see Adax WiFi app, Account Section)
```suggestion
    account_id: "112395"  # replace with your account ID (see Adax WiFi app, Account Section)
```

2020-09-21 14:10 UTC, merged